#!/bin/bash
# Models-only snapshot — champion/challenger state + history + fixtures.
#
# Regenerated by the auto-improve daemon at the end of every iteration so
# the committed file always matches the champion/challenger extractors on disk.
#
# Restore on a fresh clone:
#     make db-migrate           # apply schema first
#     make models-restore       # wraps: psql < database/models_snapshot.sql
#
# Format: plain SQL, `--data-only --column-inserts` → diff-friendly in PRs,
# schema-independent (schema comes from Alembic + `database/create_db.sql`),
# no LFS required.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_FILE="$SCRIPT_DIR/models_snapshot.sql"
CONTAINER="jobharvest-postgres"
DB_USER="jobharvest"
DB_NAME="jobharvest"

# Tables included. Order matters for TRUNCATE CASCADE but not for INSERTs
# (pg_dump emits parents-before-children). `inference_metrics_hourly` is
# excluded: it's operational latency telemetry, unbounded growth, and not
# required to reconstitute champion/challenger state on a clone.
TABLES=(
    ml_models
    model_versions
    experiments
    codex_improvement_runs
    metric_snapshots
    gold_holdout_sets
    gold_holdout_domains
    gold_holdout_jobs
    ats_pattern_proposals
    drift_baselines
    evo_individuals
    evo_cycles
    evo_population_events
)

if ! docker ps --format '{{.Names}}' | grep -q "^${CONTAINER}$"; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') - PostgreSQL container not running, skipping models dump"
    exit 0
fi

echo "$(date '+%Y-%m-%d %H:%M:%S') - Dumping models snapshot..."

TABLE_ARGS=()
for t in "${TABLES[@]}"; do
    TABLE_ARGS+=(--table="$t")
done

TRUNCATE_LIST=$(IFS=,; echo "${TABLES[*]}")
TMP="$OUTPUT_FILE.tmp"

{
    echo "-- JobHarvest champion/challenger models snapshot"
    echo "-- Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "-- Tables: ${TABLES[*]}"
    echo "-- Regenerated by backend/scripts/auto_improve_daemon.py after every iteration."
    echo "-- Restore: \`make db-migrate && make models-restore\` (see README)."
    echo ""
    echo "BEGIN;"
    echo ""
    echo "TRUNCATE TABLE ${TRUNCATE_LIST} RESTART IDENTITY CASCADE;"
    echo ""
} > "$TMP"

docker exec "$CONTAINER" pg_dump -U "$DB_USER" -d "$DB_NAME" \
    --data-only --column-inserts --no-owner --no-privileges \
    --disable-triggers \
    "${TABLE_ARGS[@]}" >> "$TMP" 2>/dev/null

echo "" >> "$TMP"
echo "COMMIT;" >> "$TMP"

mv "$TMP" "$OUTPUT_FILE"
SIZE=$(du -h "$OUTPUT_FILE" | cut -f1)
echo "$(date '+%Y-%m-%d %H:%M:%S') - Models snapshot written: $SIZE"
