-- JobHarvest champion/challenger models snapshot
-- Generated: 2026-04-14T14:37:00Z
-- Tables: ml_models model_versions experiments codex_improvement_runs metric_snapshots gold_holdout_sets gold_holdout_domains gold_holdout_jobs ats_pattern_proposals drift_baselines
-- Regenerated by backend/scripts/auto_improve_daemon.py after every iteration.
-- Restore: `make db-migrate && make models-restore` (see README).

BEGIN;

TRUNCATE TABLE ml_models,model_versions,experiments,codex_improvement_runs,metric_snapshots,gold_holdout_sets,gold_holdout_domains,gold_holdout_jobs,ats_pattern_proposals,drift_baselines RESTART IDENTITY CASCADE;

--
-- PostgreSQL database dump
--

\restrict UnlASrRryB5Gfe58rTbfuA0ytqTw0NnJGMZnDvfb7bBgRaKBEJ1jae9LkpL0P0i

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: ats_pattern_proposals; Type: TABLE DATA; Schema: public; Owner: -
--

SET SESSION AUTHORIZATION DEFAULT;

ALTER TABLE public.ats_pattern_proposals DISABLE TRIGGER ALL;



ALTER TABLE public.ats_pattern_proposals ENABLE TRIGGER ALL;

--
-- Data for Name: ml_models; Type: TABLE DATA; Schema: public; Owner: -
--

ALTER TABLE public.ml_models DISABLE TRIGGER ALL;

INSERT INTO public.ml_models (id, name, model_type, description, config, status, version, is_active, created_at, updated_at) VALUES ('e952163e-b114-40cf-9d83-78372d587a49', 'v7.0', 'tiered_extractor', 'v7.0: Codex auto-improve recovery (parent run timed out at 20min, file complete + imports cleanly). Inherits v16, delegates to v69 + applies bounded post-processing.', 'null', 'tested', 1, true, '2026-04-14 14:00:08.938098+00', '2026-04-14 14:01:46.902896+00');
INSERT INTO public.ml_models (id, name, model_type, description, config, status, version, is_active, created_at, updated_at) VALUES ('b2287fd6-8c50-458f-8549-679660a25ee6', 'v7.0', 'tiered_extractor', 'v7.0: Codex auto-improve. See memory for details.', 'null', 'new', 1, true, '2026-04-14 14:36:59.462959+00', '2026-04-14 14:36:59.462959+00');
INSERT INTO public.ml_models (id, name, model_type, description, config, status, version, is_active, created_at, updated_at) VALUES ('bf05d0fd-db10-497f-a895-c461f8869854', 'v6.9', 'tiered_extractor', 'v6.9: Codex auto-improve. See memory for details.', 'null', 'live', 1, true, '2026-04-07 09:19:41.453683+00', '2026-04-14 11:34:31.906649+00');


ALTER TABLE public.ml_models ENABLE TRIGGER ALL;

--
-- Data for Name: codex_improvement_runs; Type: TABLE DATA; Schema: public; Owner: -
--

ALTER TABLE public.codex_improvement_runs DISABLE TRIGGER ALL;

INSERT INTO public.codex_improvement_runs (id, source_model_id, test_run_id, output_model_id, status, description, source_model_name, output_model_name, test_winner, error_message, started_at, completed_at, created_at) VALUES ('7976fa2b-21a5-40d7-9c3a-6ae597e678d2', 'bf05d0fd-db10-497f-a895-c461f8869854', 'c1f3caac-ff49-44ea-bd51-b477b40a9d8b', NULL, 'failed', NULL, 'v6.9', NULL, 'challenger', 'Codex failed with exit code None', '2026-04-14 13:23:42.135887+00', '2026-04-14 13:44:20.894047+00', '2026-04-14 13:23:42.138886+00');
INSERT INTO public.codex_improvement_runs (id, source_model_id, test_run_id, output_model_id, status, description, source_model_name, output_model_name, test_winner, error_message, started_at, completed_at, created_at) VALUES ('b58ebcb4-7963-421c-9982-272f6ddfd13d', 'bf05d0fd-db10-497f-a895-c461f8869854', 'c1f3caac-ff49-44ea-bd51-b477b40a9d8b', NULL, 'completed', 'Targeted 4 failing sites (Hohepa Canterbury, The Salvation Army Hong Kong and Macau Command, CareerLink, Hays Malaysia). 2 gaps (Juvare, DigiMonk). I confirmed the prior long-running process is terminated. I’m now checking the wrapper/context files to verify the exact root-cause pattern and decide whether a small precision guard should be added before final validation. Previous accuracy: 25%, volume: 66%.', 'v6.9', 'v7.0', 'challenger', NULL, '2026-04-14 14:01:59.507113+00', '2026-04-14 14:13:07.543212+00', '2026-04-14 14:01:59.508565+00');
INSERT INTO public.codex_improvement_runs (id, source_model_id, test_run_id, output_model_id, status, description, source_model_name, output_model_name, test_winner, error_message, started_at, completed_at, created_at) VALUES ('88e75105-eeba-43b3-85dc-69010468c715', 'bf05d0fd-db10-497f-a895-c461f8869854', 'c1f3caac-ff49-44ea-bd51-b477b40a9d8b', NULL, 'cancelled', NULL, 'v6.9', NULL, 'challenger', 'Daemon was killed; cancelled stale run', '2026-04-14 14:15:40.051408+00', NULL, '2026-04-14 14:15:40.05306+00');
INSERT INTO public.codex_improvement_runs (id, source_model_id, test_run_id, output_model_id, status, description, source_model_name, output_model_name, test_winner, error_message, started_at, completed_at, created_at) VALUES ('1f6eafce-bc32-4fc8-95b2-9850bc4ec517', 'bf05d0fd-db10-497f-a895-c461f8869854', 'c1f3caac-ff49-44ea-bd51-b477b40a9d8b', NULL, 'cancelled', NULL, 'v6.9', NULL, 'challenger', 'Daemon was killed; cancelled stale run', '2026-04-14 14:18:46.542776+00', NULL, '2026-04-14 14:18:46.544604+00');
INSERT INTO public.codex_improvement_runs (id, source_model_id, test_run_id, output_model_id, status, description, source_model_name, output_model_name, test_winner, error_message, started_at, completed_at, created_at) VALUES ('803f1151-1170-4dc2-bc9a-985c3212949f', 'bf05d0fd-db10-497f-a895-c461f8869854', '91dd6b40-2e4e-4064-be0d-75807c8db308', NULL, 'cancelled', NULL, 'v6.9', NULL, 'champion', 'Cancelled stale run (newer iteration superseded this one)', '2026-04-14 14:23:03.161682+00', NULL, '2026-04-14 14:23:03.164106+00');
INSERT INTO public.codex_improvement_runs (id, source_model_id, test_run_id, output_model_id, status, description, source_model_name, output_model_name, test_winner, error_message, started_at, completed_at, created_at) VALUES ('72d20abf-b178-47ab-92f4-d59f129277f2', 'bf05d0fd-db10-497f-a895-c461f8869854', '91dd6b40-2e4e-4064-be0d-75807c8db308', NULL, 'cancelled', NULL, 'v6.9', NULL, 'champion', 'Cancelled stale run (newer iteration superseded this one)', '2026-04-14 14:25:14.562488+00', NULL, '2026-04-14 14:25:14.56399+00');
INSERT INTO public.codex_improvement_runs (id, source_model_id, test_run_id, output_model_id, status, description, source_model_name, output_model_name, test_winner, error_message, started_at, completed_at, created_at) VALUES ('4c0c11ea-7452-4f2c-b68e-497d220c4174', 'bf05d0fd-db10-497f-a895-c461f8869854', '91dd6b40-2e4e-4064-be0d-75807c8db308', 'b2287fd6-8c50-458f-8549-679660a25ee6', 'completed', 'Targeted 4 failing sites (Universidad CETYS, TD Bank, Hohepa Canterbury, Publicis.Sapient). 4 gaps (Juvare, Wem Civil, DigiMonk, PACE Development). I’ve isolated the root causes in the fixtures: two “hard fail” pages are fetch blockers (`captcha` and `connection refused`), while the actionable bespoke gap is career-hub pages that link to real job listing subpages (for example Publicis Sapient... Previous accuracy: 18%, volume: 13%.', 'v6.9', 'v7.0', 'champion', NULL, '2026-04-14 14:25:59.561505+00', '2026-04-14 14:37:00.471704+00', '2026-04-14 14:25:59.562819+00');


ALTER TABLE public.codex_improvement_runs ENABLE TRIGGER ALL;

--
-- Data for Name: drift_baselines; Type: TABLE DATA; Schema: public; Owner: -
--

ALTER TABLE public.drift_baselines DISABLE TRIGGER ALL;



ALTER TABLE public.drift_baselines ENABLE TRIGGER ALL;

--
-- Data for Name: gold_holdout_sets; Type: TABLE DATA; Schema: public; Owner: -
--

ALTER TABLE public.gold_holdout_sets DISABLE TRIGGER ALL;

INSERT INTO public.gold_holdout_sets (id, name, description, source, market_id, is_frozen, frozen_at, is_active, created_at) VALUES ('53191efe-fedf-431b-80c9-641e0f799f10', 'au_baseline_v1', 'AU gold holdout v1 — company career sites only, filtered against aggregators + blocked domains', 'lead_imports', 'AU', true, '2026-04-14 11:48:06.123227+00', true, '2026-04-14 11:44:47.787553+00');


ALTER TABLE public.gold_holdout_sets ENABLE TRIGGER ALL;

--
-- Data for Name: model_versions; Type: TABLE DATA; Schema: public; Owner: -
--

ALTER TABLE public.model_versions DISABLE TRIGGER ALL;

INSERT INTO public.model_versions (id, name, version, algorithm, artifact_path, config, feature_set, training_corpus_hash, parent_version_id, status, trained_at, promoted_at, retired_at, notes) VALUES ('41c7897c-9e61-41b7-b8cf-5cda7fc6b857', 'tiered_extractor', 1, 'heuristic_tiered_v69', 'backend/app/crawlers/tiered_extractor_v69.py', '{"module": "app.crawlers.tiered_extractor_v69", "class_name": "TieredExtractorV69", "finder_class": "CareerPageFinderV69", "finder_module": "app.crawlers.career_page_finder_v69", "benchmark_sites": 179, "composite_score": 85.4, "benchmark_run_id": "c1f3caac-ff49-44ea-bd51-b477b40a9d8b", "composite_breakdown": {"discovery": 100.0, "volume_accuracy": 96.2, "field_completeness": 45.3, "quality_extraction": 100.0}}', '["parent_v1_6_heuristic", "structured_json_ld", "ats_extractors", "dom_fallbacks"]', NULL, NULL, 'champion', '2026-04-14 11:53:47.486348+00', '2026-04-14 11:53:47.510275+00', NULL, 'Crowned 2026-04-14 after objective re-scoring of full iteration history. Composite 85.4.');


ALTER TABLE public.model_versions ENABLE TRIGGER ALL;

--
-- Data for Name: experiments; Type: TABLE DATA; Schema: public; Owner: -
--

ALTER TABLE public.experiments DISABLE TRIGGER ALL;



ALTER TABLE public.experiments ENABLE TRIGGER ALL;

--
-- Data for Name: gold_holdout_domains; Type: TABLE DATA; Schema: public; Owner: -
--

ALTER TABLE public.gold_holdout_domains DISABLE TRIGGER ALL;

INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('9838549e-b924-4eda-8f7c-99c430121f3d', '53191efe-fedf-431b-80c9-641e0f799f10', 'smartjobs.qld.gov.au', 'Queensland Government', 13870, 'AU', NULL, '97ad2324-7ff4-4b28-b349-0cef1b8ebb4c', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('2100c8fe-d867-4fc4-964a-589910562ea5', '53191efe-fedf-431b-80c9-641e0f799f10', 'dominos-australia.applynow.net.au', 'Domino''s Pizza AU', 4407, 'AU', NULL, '7b2f01b6-b301-425f-a0dd-74c086c23ea1', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('be96d668-2a0b-4499-9a6b-a855ec5117ca', '53191efe-fedf-431b-80c9-641e0f799f10', 'swinjobs.nga.net.au', 'Swinburne University of Technology', 3674, 'AU', NULL, '546494d3-3946-405a-9fdb-20718793d7ca', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('97662c15-1a5c-44a2-949c-c5450e64dfaf', '53191efe-fedf-431b-80c9-641e0f799f10', 'ecu.nga.net.au', 'Edith Cowan University', 3410, 'AU', NULL, '786ff66a-03ec-4963-bba9-460c3bf45b67', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('126394d1-7467-4a5e-8607-14f98ced8ed1', '53191efe-fedf-431b-80c9-641e0f799f10', 'careers.vic.gov.au', 'Victorian Government', 2810, 'AU', NULL, 'a44e79c4-320c-4225-adc3-544a045e256f', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('f7e934b3-74e4-4f1a-b821-698c589bc2b4', '53191efe-fedf-431b-80c9-641e0f799f10', 'colescareers.com.au', 'Coles Group', 2630, 'AU', NULL, '4e7f6dfc-5943-4a89-8311-d53e1787aa67', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('8fc85c65-a627-4d12-bd19-382f4cf9c502', '53191efe-fedf-431b-80c9-641e0f799f10', 'careers.goodstart.org.au', 'Goodstart Early Learning', 2620, 'AU', NULL, 'ca198d48-2c80-4e28-a311-d5c296da4ae4', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('e138730b-bf89-407b-b3d2-501ca51560c2', '53191efe-fedf-431b-80c9-641e0f799f10', 'amazon.jobs', 'Amazon Web Services (AWS)', 2450, 'AU', NULL, 'db11163a-9278-4594-90d5-69a3ea47ac88', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('6f7d9502-13f0-47e8-aaeb-064436677928', '53191efe-fedf-431b-80c9-641e0f799f10', 'careers.g8education.edu.au', 'G8 Education Limited', 2175, 'AU', NULL, '48b9f02f-d9ff-4344-b38b-534ac0fae030', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('a0b46cf8-7d98-4dc9-b10d-8b09b485b4a4', '53191efe-fedf-431b-80c9-641e0f799f10', 'jobs.deloitte.com.au', 'Deloitte', 2167, 'AU', NULL, 'de6d827a-6697-498c-bfbf-9eadbb8d56b4', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('39a2650f-08ca-4d23-8d3b-8820ed7fedbf', '53191efe-fedf-431b-80c9-641e0f799f10', 'careers.woolworthsgroup.com.au', 'PFD Food Services Pty Ltd', 1957, 'AU', NULL, '53a88c9f-5283-4502-b5fa-c7555f954517', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('95949eb4-fdf2-4033-81c4-2eeb683b563e', '53191efe-fedf-431b-80c9-641e0f799f10', 'careers.mcdonalds.com.au', 'McDonald''s', 1900, 'AU', NULL, '8ee15691-637e-4e02-85a6-dba7b28586c5', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('67b10ab0-4336-484f-a7d6-48d93a4ec82b', '53191efe-fedf-431b-80c9-641e0f799f10', 'jobs.health.nsw.gov.au', 'South Western Sydney Local Health District', 1710, 'AU', NULL, '5f632a1b-b706-4b87-b45f-c05d7413b9b1', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('d1cb4752-fbb9-4df9-bc85-729d52ddbb6f', '53191efe-fedf-431b-80c9-641e0f799f10', 'hays.com.au', 'Hays', 1640, 'AU', NULL, 'cf167f79-7de8-4723-9c67-b664e03610ca', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('559928b4-f5f7-4630-8df5-7c615afe8c25', '53191efe-fedf-431b-80c9-641e0f799f10', 'careers.nab.com.au', 'NAB', 1549, 'AU', NULL, '58014857-bc31-4adb-833d-089a84d4421a', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('3ba0d878-f165-415f-87d2-d4c9d209b7ad', '53191efe-fedf-431b-80c9-641e0f799f10', 'jobs.dcj.nsw.gov.au', 'NSW Department of Communities and Justice', 1523, 'AU', NULL, '49f5d235-959f-4393-9655-33b17f5e5bf1', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('8840de9d-06d4-4aa0-9324-fdb48b6d9668', '53191efe-fedf-431b-80c9-641e0f799f10', 'external-careers.jobs.unsw.edu.au', 'University of New South Wales', 1506, 'AU', NULL, 'dec3813f-d95e-4731-9205-6d67f1c0f226', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('5f943759-f509-4c38-9193-462567fa5f17', '53191efe-fedf-431b-80c9-641e0f799f10', 'careers.marriott.com', 'Marriott International', 1470, 'AU', NULL, 'cc2bbfa2-c76d-48d3-a637-d6279e7431a2', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('920e7929-cb97-4cf1-a74c-281fa0273919', '53191efe-fedf-431b-80c9-641e0f799f10', 'jobs.transport.nsw.gov.au', 'Transport for NSW', 1365, 'AU', NULL, '934a82c4-351d-470c-a913-033669132944', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('a4c8dd69-ce3a-46ed-8f2f-111efdf2baa8', '53191efe-fedf-431b-80c9-641e0f799f10', 'moirajobslink.com.au', 'Moira Jobs Link', 1361, 'AU', NULL, '210e3128-aea6-4130-b132-58493431b715', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('c843a65b-e631-468c-ae40-0d884f916ff3', '53191efe-fedf-431b-80c9-641e0f799f10', 'jobs.careers.vic.gov.au', 'Department of Justice and Community Safety', 1354, 'AU', NULL, '0aff329e-da6a-4e48-9c31-7865abfada83', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('3a8b810b-bb4c-4814-9300-6bd7e3a83edc', '53191efe-fedf-431b-80c9-641e0f799f10', 'careers.pageuppeople.com', 'Ramsay Health Care', 1316, 'AU', NULL, '7c118ffb-5b05-4457-acc0-2a4f28b10eee', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('7014a4e4-8852-44a9-972a-1d48b3ddfc7a', '53191efe-fedf-431b-80c9-641e0f799f10', 'fa-exfs-saasfaprod1.fa.ocs.oraclecloud.com', 'Downer Group', 1264, 'AU', NULL, '8c6b8f32-0443-421e-8829-20a7c72750ee', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('129c192f-f5c5-4db7-a7ba-3d3f7f42a4bf', '53191efe-fedf-431b-80c9-641e0f799f10', 'recruitment.macquarie.com', 'Macquarie Group Limited', 1245, 'AU', NULL, 'e25473c5-5969-4985-b4bc-40a79cd890fe', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('471c8bc6-85fd-4e80-8bbe-d2dcf9a2747b', '53191efe-fedf-431b-80c9-641e0f799f10', 'jobs-au.pwc.com', 'PwC', 1156, 'AU', NULL, 'b55f4583-52cc-49ed-b1ef-ae0ec6d591b0', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('0d3e7476-3e6b-4496-9e71-b3bf737e9dfb', '53191efe-fedf-431b-80c9-641e0f799f10', 'ebuu.fa.ap1.oraclecloud.com', 'Westpac', 1119, 'AU', NULL, '94298d0b-5c73-4f67-aa41-0462144194a7', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('de3db1c1-5893-4203-84e0-f289f8109c8d', '53191efe-fedf-431b-80c9-641e0f799f10', 'careers.anz.com', 'ANZ Banking group', 1088, 'AU', NULL, '2e099750-3ad0-42b5-9dc3-fff06f4baf69', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('676153dc-c90e-4d2e-9ee2-4de713423c29', '53191efe-fedf-431b-80c9-641e0f799f10', 'jobsearch.baesystems.com', 'BAE Systems', 1081, 'AU', NULL, '354b9fb0-9bc0-4135-81de-d47cdd4962dc', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('de972de2-c553-45f9-845a-8d55b084fb80', '53191efe-fedf-431b-80c9-641e0f799f10', 'jobs.ventia.com', 'Ventia', 1066, 'AU', NULL, '8d7207e6-b5b8-4654-a0c5-cfb3f4778e73', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('dd216dfd-3914-42a6-9793-3eb4bf15be34', '53191efe-fedf-431b-80c9-641e0f799f10', 'careers.stryker.com', 'Stryker', 1060, 'AU', NULL, 'aab1a821-1515-4020-bb09-0fa7fb3d3919', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('5a25d021-291c-4a0f-9ab4-dca0b8a4e0a8', '53191efe-fedf-431b-80c9-641e0f799f10', 'careers.bhp.com', 'BHP', 1059, 'AU', NULL, '87a9b05b-961e-4f82-8078-f8ee73e7e6f9', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('a7b52b7e-3f47-43a4-80ca-e04fd30e7159', '53191efe-fedf-431b-80c9-641e0f799f10', 'search.jobs.wa.gov.au', 'Western Australia Government', 1039, 'AU', NULL, 'b155a1e7-010b-4ce3-b68d-49ef30a674da', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('da65427a-be8f-4031-a649-4da84f3bbce8', '53191efe-fedf-431b-80c9-641e0f799f10', 'accenture.com', 'Accenture', 1028, 'AU', NULL, 'f37c02f0-1849-4ef5-a952-fcdb3938fc82', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('c8747c07-56a5-4aea-a0f0-3d405b1cfe03', '53191efe-fedf-431b-80c9-641e0f799f10', 'endeavourgroupcareers.com.au', 'BWS', 1019, 'AU', NULL, '08de521d-4847-432d-942e-7ccb67993ff5', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('45d986d6-c924-4ea7-b0c5-9446ed28c42b', '53191efe-fedf-431b-80c9-641e0f799f10', 'shellenergy.wd105.myworkdayjobs.com', 'Shell Energy', 1000, 'AU', NULL, 'c11cfe0b-2597-4801-9661-48cd0b571efc', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('82eed7af-74b7-4688-a1e2-585a9bf0c51f', '53191efe-fedf-431b-80c9-641e0f799f10', 'federalhospitalitycareers.com.au', 'Federal Group', 1000, 'AU', NULL, '5e683dd3-f51d-450d-80ef-eccbf2b0eaa5', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('6651ece3-cf0c-4614-a6c9-25db59f67c16', '53191efe-fedf-431b-80c9-641e0f799f10', 'adfhr.elmotalent.com.au', 'Alcohol and Drug Foundation', 1000, 'AU', NULL, 'eaeeb89a-138c-4c4b-8b26-7413b2f5fd59', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('d06941aa-43c0-47b8-8fbc-d5d110fc5f43', '53191efe-fedf-431b-80c9-641e0f799f10', 'carma.pinpointhq.com', 'Carma', 1000, 'AU', NULL, 'ffde5628-e7ff-4722-9711-27615d4b4953', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('e3f9d299-4744-4082-a0b1-cd95a02e5408', '53191efe-fedf-431b-80c9-641e0f799f10', 'benedict.elmotalent.com.au', 'Benedict Industries', 1000, 'AU', NULL, 'd0228435-c1fc-41d0-a29c-48018182f901', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('ca9074c2-d8fa-41cf-8d17-36a0d0ba6dda', '53191efe-fedf-431b-80c9-641e0f799f10', 'ilsc.gov.au', 'Indigenous Land and Sea Corporation', 1000, 'AU', NULL, 'c3f011e9-340f-4213-a901-1c19ff524d16', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('9e3b9d48-64f7-44a3-a330-a081a8104fb6', '53191efe-fedf-431b-80c9-641e0f799f10', 'jacobgroup.org', 'Jacob Group of Companies', 1000, 'AU', NULL, 'c10e2788-260e-4a8e-8fad-18b3de2f0e6c', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('3940317a-e82b-4040-8255-731874b41ab5', '53191efe-fedf-431b-80c9-641e0f799f10', 'lithgow.applynow.net.au', 'Lithgow City Council', 1000, 'AU', NULL, '64afef6f-eb9c-43e3-96d0-7bd5488c45c4', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('d9f6e7de-5a34-4650-9f8b-45c615024fc0', '53191efe-fedf-431b-80c9-641e0f799f10', 'algettshirecouncil.applynow.net.au', 'Walgett Shire Council', 1000, 'AU', NULL, '0adb5851-c0fa-4acc-9a82-9cb135407dc0', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('f968da15-9190-4375-b105-cf4fcf9ececb', '53191efe-fedf-431b-80c9-641e0f799f10', 'rinnaiaustralia.recruitmenthub.com.au', 'Rinnai Australia', 1000, 'AU', NULL, '4af2b326-7f1c-4ca5-b5b2-2afc7c9f332f', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('5ca42037-5feb-452e-a307-39cd5a60daee', '53191efe-fedf-431b-80c9-641e0f799f10', 'altius-group.com.au', 'Altius Group', 1000, 'AU', NULL, '9cfdde9e-c489-4077-bb10-911d8a1707ff', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('7535c6bc-94bc-4541-bacf-da5ed6a43600', '53191efe-fedf-431b-80c9-641e0f799f10', 'buildsafe.bamboohr.com', 'Buildsafe Australia', 1000, 'AU', NULL, '43cf9adc-c660-48c4-b7a0-f88d857291c1', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('355b37a3-6d52-4b9a-884c-300373c1fb9f', '53191efe-fedf-431b-80c9-641e0f799f10', 'micare.expr3ss.com', 'MiCare', 1000, 'AU', NULL, '922ac5e1-f828-4e16-8f7e-a351da7f493c', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('c14c389b-6a10-46c6-9fa1-78bd815e5d2e', '53191efe-fedf-431b-80c9-641e0f799f10', 'raeline.expr3ss.com', 'Rae-Line', 1000, 'AU', NULL, '17d34891-d2fd-4c26-90eb-e1c7b995ccc0', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('7a26fe01-5998-40f2-8700-5add0eafbce5', '53191efe-fedf-431b-80c9-641e0f799f10', 'mlc.org.au', 'Marrickville Legal Centre', 1000, 'AU', NULL, '187b6ca9-0c76-4465-81b8-3d1223751fe3', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('defe4252-3172-4282-b2f8-a1bf9ebccad7', '53191efe-fedf-431b-80c9-641e0f799f10', 'genwest.org.au', 'GenWest', 1000, 'AU', NULL, '59f1adcb-c4b2-45e2-ae28-ff57285e2836', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('df636250-e166-44ed-89b4-cca2f796138e', '53191efe-fedf-431b-80c9-641e0f799f10', 'resourcerecoverygroup.com.au', 'Resource Recovery Group', 1000, 'AU', NULL, 'e5bd76fa-0627-4dc2-9147-80196707bc01', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('8625357d-0943-45c7-8f60-93671febdfc8', '53191efe-fedf-431b-80c9-641e0f799f10', 'sentia.com.au', 'Sentia Australia', 1000, 'AU', NULL, '0047ebc5-7f66-429d-a418-e75ade521230', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('9d261a65-446f-4560-b5ce-572f25638805', '53191efe-fedf-431b-80c9-641e0f799f10', 'pathfinders.ngo', 'Pathfinders', 1000, 'AU', NULL, 'ed5b2c9b-761f-4c40-a02d-f3745dfe8676', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('a6bd2c7d-a961-47e0-a25c-17f2450f68be', '53191efe-fedf-431b-80c9-641e0f799f10', 'shdh.org.au', 'Swan Hill District Health', 1000, 'AU', NULL, '5aec8837-de73-4378-8028-588295128884', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('6078483b-f65e-4a77-a9b2-1ee799006b25', '53191efe-fedf-431b-80c9-641e0f799f10', 'merivale.com.au', 'Merivale', 1000, 'AU', NULL, '811d108f-fa28-4de3-9bb5-4e457facd7be', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('c93606b5-e91e-492b-a93b-93a335037929', '53191efe-fedf-431b-80c9-641e0f799f10', 'confidentialcc.worldmanager.com', 'veronika maine', 1000, 'AU', NULL, '824d0a2a-e6cb-4cdc-b959-01d197e5d6a1', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('90aa3ab8-4ffa-4d0b-90db-a693ea801bca', '53191efe-fedf-431b-80c9-641e0f799f10', 'careers.volkswagen.net.au', 'Volkswagen Group Australia', 1000, 'AU', NULL, '2128916d-e156-4179-9d18-d1744d9ee19e', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('b86d6de9-1581-412b-9538-e6819df8fc83', '53191efe-fedf-431b-80c9-641e0f799f10', 'careers.nhvr.gov.au', 'National Heavy Vehicle Regulator', 1000, 'AU', NULL, '203bd676-ea96-4909-985a-43dd98d864b9', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('a7107800-e48f-4a53-b604-f8c57d037691', '53191efe-fedf-431b-80c9-641e0f799f10', 'jobs.esta.vic.gov.au', 'Emergency Services Telecommunications Authority', 1000, 'AU', NULL, '3718edea-395f-4619-b741-2c50d272d516', 'unverified', NULL, NULL);
INSERT INTO public.gold_holdout_domains (id, holdout_set_id, domain, advertiser_name, expected_job_count, market_id, ats_platform, source_lead_import_id, verification_status, verified_at, verified_by) VALUES ('9334a892-1ea3-4d0e-a5dd-170ebfa00a5d', '53191efe-fedf-431b-80c9-641e0f799f10', 'equest.com', 'eQuest Global Job Posting Distribution', 1000, 'AU', NULL, '4a324d0c-2177-498b-a31d-8139937ddc21', 'unverified', NULL, NULL);


ALTER TABLE public.gold_holdout_domains ENABLE TRIGGER ALL;

--
-- Data for Name: gold_holdout_jobs; Type: TABLE DATA; Schema: public; Owner: -
--

ALTER TABLE public.gold_holdout_jobs DISABLE TRIGGER ALL;



ALTER TABLE public.gold_holdout_jobs ENABLE TRIGGER ALL;

--
-- Data for Name: metric_snapshots; Type: TABLE DATA; Schema: public; Owner: -
--

ALTER TABLE public.metric_snapshots DISABLE TRIGGER ALL;



ALTER TABLE public.metric_snapshots ENABLE TRIGGER ALL;

--
-- PostgreSQL database dump complete
--

\unrestrict UnlASrRryB5Gfe58rTbfuA0ytqTw0NnJGMZnDvfb7bBgRaKBEJ1jae9LkpL0P0i


COMMIT;
