"""Silver-label support on gold_holdout_jobs + site_wrapper link.

Adds:
  - gold_holdout_jobs.verification_status    ('silver' | 'suspect' | 'gold' | 'unverified')
  - gold_holdout_jobs.source                  (where the label came from: 'baseline_wrapper', 'manual', ...)
  - gold_holdout_jobs.source_url              (per-job URL — baseline wrappers emit this)
  - gold_holdout_jobs.description_length      (sanity check for the silver extractor)

Silver labels are generated by running Jobstream's hand-tuned wrappers (in
`site_wrapper_test_data`) against stored holdout snapshots. They multiply the
eval set ~10x without manual labelling effort — the tradeoff is encoded in
the `verification_status` column so consumers can weight gold above silver.

Revision ID: 0027
Revises: 0026
"""

from alembic import op


revision = "0027"
down_revision = "0026"
branch_labels = None
depends_on = None


def upgrade():
    op.execute("""
        ALTER TABLE gold_holdout_jobs
            ADD COLUMN IF NOT EXISTS verification_status TEXT NOT NULL DEFAULT 'unverified',
            ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'manual',
            ADD COLUMN IF NOT EXISTS source_url TEXT,
            ADD COLUMN IF NOT EXISTS description_length INTEGER
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_gold_holdout_jobs_verification_status
            ON gold_holdout_jobs (verification_status)
    """)
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_gold_holdout_jobs_source
            ON gold_holdout_jobs (source)
    """)


def downgrade():
    op.execute("DROP INDEX IF EXISTS ix_gold_holdout_jobs_source")
    op.execute("DROP INDEX IF EXISTS ix_gold_holdout_jobs_verification_status")
    op.execute("""
        ALTER TABLE gold_holdout_jobs
            DROP COLUMN IF EXISTS description_length,
            DROP COLUMN IF EXISTS source_url,
            DROP COLUMN IF EXISTS source,
            DROP COLUMN IF EXISTS verification_status
    """)
